version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: "postgres.dev"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
